fail_fast: true

repos:
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.942
    hooks:
        - id: mypy
          exclude: flipper_client\.egg_info|build|.circleci
          args:
            - --follow-imports=silent
            - --ignore-missing-imports
  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.1.13
    hooks:
      - id: insert-license
        files: flipper
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: end-of-file-fixer
        exclude: flipper_thrift|flipper_client\.egg_info|build|.circleci
      - id: trailing-whitespace
        exclude: flipper_thrift|flipper_client\.egg_info|build|.circleci
      - id: check-ast
        exclude: flipper_thrift|flipper_client\.egg_info|build|.circleci
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.4
    hooks:
      - id: bandit
        files: ^flipper$
  - repo: https://github.com/abravalheri/validate-pyproject
    rev: v0.24.1
    hooks:
      - id: validate-pyproject
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.8
    hooks:
      - id: ruff-format
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
